version: '3'

services:
  api:
    build: ./starter/.
    container_name: api-container
    environment:
      - CONNEXION_DB_USER=${POSTGRES_USER}
      - CONNEXION_DB_PASSWORD=${POSTGRES_PASSWORD}
      - CONNEXION_DB_NAME=${POSTGRES_DB}
      - CONNEXION_DB_PORT=${PORT_DB}
      - CONNEXION_DB_HOST=db
    ports:
      - "8080:${PORT_API}"
    depends_on:
      - db
    restart: always

  db:
    build: ./database_script/.
    container_name: postgresql-container
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:${PORT_DB}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-data:
