version: '3'

services:
  front:
    build: ./front/front-api/.
    container_name: react-app
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./front/front-api/src:/app/src
    ports:
      - "3000:3000"
    depends_on:
      - api

  api:
    build: ./starter/.
    container_name: api-container
    environment:
      - CONNEXION_DB_USER=${POSTGRES_USER}
      - CONNEXION_DB_PASSWORD=${POSTGRES_PASSWORD}
      - CONNEXION_DB_NAME=${POSTGRES_DB}
      - CONNEXION_DB_PORT=${PORT_DB}
      - CONNEXION_DB_HOST=db
      - PORT_API=${PORT_API}
    ports:
      - "${PORT_API}:8080"
    depends_on:
      - db
    restart: always

  db:
    build: ./database_script/.
    container_name: postgresql-container
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${PORT_DB}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-data:
